services:
  - type: web
    name: your-backend-service-name  # Replace with your Render service name
    env: maven
    buildCommand: chmod +x mvnw && ./mvnw clean package
    startCommand: java -jar target/*.jar
    runtime: java
    javaVersion: 17